export const participants = [
    {
        name: 'Fahfnyr',
        avatar: null,
        team: 'Don taveine',
        twitch_url: null,
    },
    {
        name: 'Kanif',
        avatar: null,
        team: 'Don taveine',
        twitch_url: null,
    },
    {
        name: 'KrapoPlay',
        avatar: '/image/pp/KrapoPlay.png',
        team: 'Don taveine',
        twitch_url: 'https://www.twitch.tv/krapoplay_fr',
    },
    {
        name: 'Pawm',
        avatar: '/image/pp/Pawn.jpeg',
        team: 'Don taveine',
        twitch_url: 'https://www.twitch.tv/pawm__',
    },
    {
        name: 'AlphaCast',
        avatar: '/image/pp/Alphacast.png',
        team: 'Les CommerSang',
        twitch_url: 'https://www.twitch.tv/alphacast',
    },
    {
        name: 'M4f',
        avatar: '/image/pp/M4f.png',
        team: 'Les CommerSang',
        twitch_url: 'https://www.twitch.tv/M4fgaming',
    },
    {
        name: 'Bobby Vulgrif',
        avatar: '/image/pp/BobbyVulgrif.png',
        team: 'Les CommerSang',
        twitch_url: 'https://www.twitch.tv/bobbyvulgrif',
    },
    {
        name: 'Pressea',
        avatar: '/image/pp/Pressea.jpeg',
        team: 'Les CommerSang',
        twitch_url: 'https://www.twitch.tv/pressea',
    },
    {
        name: 'iMeelk',
        avatar: '/image/pp/iMeelk.png',
        team: 'Maison Frey',
        twitch_url: 'https://www.twitch.tv/imeelk',
    },
    {
        name: 'Areliann',
        avatar: '/image/pp/Areliann.png',
        team: 'Maison Frey',
        twitch_url: 'https://www.twitch.tv/areliann',
    },
    {
        name: 'Teyz',
        avatar: '/image/pp/Teyzouu.png',
        team: 'Maison Frey',
        twitch_url: 'https://www.twitch.tv/teyzouu',
    },
    {
        name: 'Snake',
        avatar: '/image/pp/snake.png',
        team: 'Maison Frey',
        twitch_url: 'https://www.twitch.tv/v_snakee',
    },
    {
        name: 'Hugolisoir',
        avatar: '/image/pp/Hugolisoir.png',
        team: 'Les saigneurs Veinard',
        twitch_url: 'https://www.twitch.tv/hugolisoir',
    },
    {
        name: 'CaptainFracas',
        avatar: '/image/pp/CaptainFracas.png',
        team: 'Les saigneurs Veinard',
        twitch_url: 'https://www.twitch.tv/captainfracas',
    },
    {
        name: 'WaterPatate',
        avatar: '/image/pp/WaterPatate.png',
        team: 'Les saigneurs Veinard',
        twitch_url: 'https://www.twitch.tv/waterpatate',
    },
    {
        name: 'Furgoth',
        avatar: '/image/pp/Furgoth.png',
        team: 'Les saigneurs Veinard',
        twitch_url: 'https://www.twitch.tv/furgoth',
    },
    {
        name: 'Shisheyu',
        avatar: '/image/pp/Shisheyu.png',
        team: 'Suceurs 200',
        twitch_url: 'https://www.twitch.tv/Shisheyu',
    },
    {
        name: 'Mynthos',
        avatar: '/image/pp/Mynthos.png',
        team: 'Suceurs 200',
        twitch_url: 'https://www.twitch.tv/Mynthos',
    },
    {
        name: 'Covfefe',
        avatar: '/image/pp/Covfefe.png',
        team: 'Suceurs 200',
        twitch_url: 'https://www.twitch.tv/Covfefe',
    },
    {
        name: 'DrFeelGood',
        avatar: '/image/pp/DrFeelGood.png',
        team: 'Suceurs 200',
        twitch_url: 'https://www.twitch.tv/DrFeelGood',
    },
    {
        name: 'OursABiere',
        avatar: '/image/pp/OursABiere.png',
        team: 'Sang Rancune',
        twitch_url: 'https://www.twitch.tv/OursABiere',
    },
    {
        name: 'Ribie',
        avatar: '/image/pp/Ribie.png',
        team: 'Sang Rancune',
        twitch_url: 'https://www.twitch.tv/Ribie',
    },
    {
        name: 'Aerzia',
        avatar: 'https://media.discordapp.net/attachments/1243572333260705943/1243574350255493171/GKGNjHjXgAEOprj.jpg?ex=6651f85d&is=6650a6dd&hm=fb748a741e5db2b8a8273f023f7081c7b03907407e3b1d78d5c9e9b6382b91a0&=&format=webp&width=842&height=1264',
        team: 'Sang Rancune',
        twitch_url: 'https://www.twitch.tv/aerzia',
    },
    {
        name: 'Desastre_Show',
        avatar: '/image/pp/Desastre_Show.png',
        team: 'Sang Rancune',
        twitch_url: 'https://www.twitch.tv/DrFeelGood',
    },
    {
        name: 'Lynkus_',
        avatar: '/image/pp/Lynkus.png',
        team: 'Rats bat joie',
        twitch_url: 'https://www.twitch.tv/Lynkus_',
    },
    {
        name: 'Lady_Emash',
        avatar: '/image/pp/Emash.png',
        team: 'Rats bat joie',
        twitch_url: 'https://www.twitch.tv/Lady_Emash',
    },
    {
        name: 'TheGreatReview',
        avatar: '/image/pp/TheGreatReview.png',
        team: 'Rats bat joie',
        twitch_url: 'https://www.twitch.tv/TheGreatReview',
    },
    {
        name: 'Tonton',
        avatar: '/image/pp/Tonton.png',
        team: 'Rats bat joie',
        twitch_url: 'https://www.twitch.tv/Tonton',
    },
    {
        name: 'Eliya',
        avatar: '/image/pp/Eliya.png',
        team: 'Les 4 Sangcou',
        twitch_url: 'https://www.twitch.tv/oo_eliya_oo',
    },
    {
        name: 'Bahamutcosplay',
        avatar: '/image/pp/Bahamut.png',
        team: 'Les 4 Sangcou',
        twitch_url: 'https://www.twitch.tv/Bahamutcosplay',
    },
    {
        name: 'Pinde',
        avatar: '/image/pp/Pinde.png',
        team: 'Les 4 Sangcou',
        twitch_url: 'https://www.twitch.tv/Pinde',
    },
    {
        name: 'Titavion',
        avatar: '/image/pp/Titavion.png',
        team: 'Les 4 Sangcou',
        twitch_url: 'https://www.twitch.tv/Titavion',
    },
    {
        name: 'Zerator',
        avatar: '/image/pp/Zerator.png',
        team: 'Les Sang Tenaires',
        twitch_url: 'https://www.twitch.tv/Zerator',
    },
    {
        name: 'Gius',
        avatar: '/image/pp/Gius.png',
        team: 'Les Sang Tenaires',
        twitch_url: 'https://www.twitch.tv/Gius',
    },
    {
        name: 'KennyStream',
        avatar: '/image/pp/KennyStream.png',
        team: 'Les Sang Tenaires',
        twitch_url: 'https://www.twitch.tv/KennyStream',
    },
    {
        name: 'Moman',
        avatar: '/image/pp/Momanus.png',
        team: 'Les Sang Tenaires',
        twitch_url: 'https://www.twitch.tv/Moman',
    },
    {
        name: 'Adyboo',
        avatar: '/image/pp/Adyboo.png',
        team: 'Donneurs Universels',
        twitch_url: 'https://www.twitch.tv/Adyboo',
    },
    {
        name: 'Kaosvmd',
        avatar: '/image/pp/Kao.jpeg',
        team: 'Donneurs Universels',
        twitch_url: 'https://www.twitch.tv/Kaosvmd',
    },
    {
        name: 'Pepipin',
        avatar: '/image/pp/Pepipin.jpeg',
        team: 'Donneurs Universels',
        twitch_url: 'https://www.twitch.tv/Pepipin',
    },
    {
        name: 'Kaela2314',
        avatar: null,
        team: 'Sang Soucis',
        twitch_url: null,
    },
    {
        name: 'Maladiu',
        avatar: null,
        team: 'Sang Soucis',
        twitch_url: null,
    },
    {
        name: 'Sansu5968',
        avatar: null,
        team: 'Sang Soucis',
        twitch_url: null,
    },
    {
        name: 'Fusiow',
        avatar: '/image/pp/Fusiow.png',
        team: 'Peau Lisse',
        twitch_url: 'https://www.twitch.tv/Fusiow',
    },
    {
        name: 'Dach',
        avatar: '/image/pp/Dach.png',
        team: 'Peau Lisse',
        twitch_url: 'https://www.twitch.tv/Dach',
    },
    {
        name: 'Eventisfr',
        avatar: '/image/pp/Eventis.png',
        team: 'Peau Lisse',
        twitch_url: 'https://www.twitch.tv/Eventisfr',
    },
    {
        name: 'Lissae',
        avatar: null,
        team: 'Peau Lisse',
        twitch_url: null,
    },
    {
        name: 'LittleBigWhale',
        avatar: '/image/pp/LittleBigWhale.png',
        team: 'Vampitres',
        twitch_url: 'https://www.twitch.tv/LittleBigWhale',
    },
    {
        name: 'Gom4rt',
        avatar: '/image/pp/Gom4rt.png',
        team: 'Vampitres',
        twitch_url: 'https://www.twitch.tv/Gom4rt',
    },
    {
        name: 'LadySundae',
        avatar: '/image/pp/LadySundae.png',
        team: 'Vampitres',
        twitch_url: 'https://www.twitch.tv/LadySundae',
    },
    {
        name: 'Shaunz',
        avatar: '/image/pp/Shaunz.png',
        team: 'Vampitres',
        twitch_url: 'https://www.twitch.tv/Shaunz',
    },
    {
        name: 'Diabalzane',
        avatar: '/image/pp/Diabalzane.png',
        team: 'Crocs Mignon',
        twitch_url: 'https://www.twitch.tv/Diabalzane',
    },
    {
        name: 'Aeterna',
        avatar: '/image/pp/AeternaLive.jpeg',
        team: 'Crocs Mignon',
        twitch_url: 'https://www.twitch.tv/AeternaLive',
    },
    {
        name: 'Finduss',
        avatar: null,
        team: 'Crocs Mignon',
        twitch_url: null,
    },
    {
        name: 'Papygato',
        avatar: null,
        team: 'Crocs Mignon',
        twitch_url: null,
    },
    {
        name: 'AntoineDaniel',
        avatar: '/image/pp/AntoineDaniel.png',
        team: 'Equipe 15',
        twitch_url: 'https://www.twitch.tv/AntoineDaniel',
    },
    {
        name: 'AngleDroit',
        avatar: '/image/pp/AngleDroit.png',
        team: 'Equipe 15',
        twitch_url: 'https://www.twitch.tv/AngleDroit',
    },
    {
        name: 'Joueur Du Grenier',
        avatar: '/image/pp/JoueurduGrenier.png',
        team: 'Equipe 15',
        twitch_url: 'https://www.twitch.tv/joueur_du_grenier',
    },
    {
        name: 'Sakor',
        avatar: '/image/pp/sakor.png',
        team: 'Equipe 15',
        twitch_url: 'https://www.twitch.tv/sakor_',
    }
];